repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
    - id: mypy
      args: [--no-strict-optional, --ignore-missing-imports]
      additional_dependencies: [cma==3.0.3,
                                numpy==1.19.5, 
                                scipy==1.5.2,
                                tensorflow==2.4.1, 
                                tensorflow-probability==0.12.1, 
                                tensorflow-estimator==2.4.0
                                ]
